---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins1-sa
      containers:
        - name: jenkins
          image: jenkins4eval/jenkins:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
          env:
            - name: LIMITS_MEMORY
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            - name: JAVA_OPTS
              value: >-
                -Xmx$(LIMITS_MEMORY)m 
                -XshowSettings:vm 
                -Dhudson.slaves.NodeProvisioner.initialDelay=0 
                -Dhudson.slaves.NodeProvisioner.MARGIN=50 
                -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 
                -Dcom.sun.jndi.ldap.connect.timeout=100
          volumeMounts:
            - name: jenkins
              mountPath: /var/jenkins_home
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl -s localhost:8080 > /dev/null
            initialDelaySeconds: 300
            timeoutSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: jenkins-pvc
