---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    name: jenkins-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 1.2.3.4 # NFS server IP
    path: /k3s/jenkins # path on nfs server for container storage
