apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  #  namespace: general
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
